### ISSUE TITLE
How to change USB device name?

### ISSUE THREAD

**Issue by tinkerBOY-git** [volium/nanoBoot#11]
I tried the bootloader on an atmega32u4 chip and Windows 10 recognized it as "USB Input Device". I want to change the usb name but im not sure how to do it.

**Comment by volium** [comment]
Hello @tinkerBOY-git, sorry for not having replied earlier, I have not been able to continue working on this project for a long time...

Anyway, well, the reason Windows shows that name, is because currently nanoBoot does not implement the "Product String Descriptor" due to size limitations. We are still very tight on space; however @sigprof has [a branch](https://github.com/sigprof/nanoBoot/tree/string-descriptors) where he has this as WIP, you may want to check that one out.

I am hopeful we can merge that back into this version at some point in the not-too-distant future 😉
